package avt;

import main.Canvas;

public final class T {
   public static String a;
   public static String b;
   public static String c;
   public static String d;
   public static String e;
   public static String f;
   public static String g;
   public static String h;
   public static String i;
   public static String j;
   public static String k;
   public static String l;
   public static String m;
   public static String n;
   public static String o;
   public static String p;
   public static String q;
   public static String r;
   public static String s;
   public static String t;
   public static String u;
   public static String v;
   public static String w;
   public static String x;
   public static String y;
   public static String z;
   public static String A;
   public static String B;
   public static String C;
   public static String D;
   public static String E;
   public static String F;
   public static String G;
   public static String H;
   public static String I;
   public static String J;
   public static String K;
   public static String L;
   public static String M;
   public static String N;
   public static String O;
   public static String P;
   public static String Q;
   public static String R;
   public static String S;
   public static String T;
   public static String U;
   public static String V;
   public static String W;
   public static String X;
   public static String Y;
   public static String Z;
   public static String aa;
   public static String ab;
   public static String ac;
   public static String ad;
   public static String ae;
   public static String af;
   public static String ag;
   public static String ah;
   public static String ai;
   public static String aj;
   public static String ak;
   public static String al;
   public static String am;
   public static String an;
   public static String ao;
   public static String ap;
   public static String aq = "vào";
   public static String ar = "/font.av";
   public static String as = "/bg.av";
   public static String at = "/home.av";
   public static String au = "/farm.av";
   public static String av = "/effect.av";
   public static String aw = "/main.av";
   public static String ax = "/dialLucky.av";
   public static String ay;
   public static String az;
   public static String aA;
   public static String aB;
   public static String aC;
   public static String aD;
   public static String aE;
   public static String aF;
   public static String aG;
   public static String aH = "http://";
   public static String aI = "@username";
   public static String aJ;
   public static String aK;
   public static String aL;
   public static String getData;
   public static String aN;
   public static String aO;
   public static String aP;
   public static String aQ;
   public static String aR;
   public static String aS;
   public static String aT;
   public static String aU;
   public static String aV;
   public static String aW;
   public static String aX;
   public static String aY;
   public static String aZ;
   public static String ba;
   public static String bb;
   public static String bc;
   public static String bd;
   public static String be;
   public static String bf;
   public static String bg;
   public static String bh;
   public static String bi;
   public static String bj;
   public static String bk;
   public static String bl;
   public static String bm;
   public static String bn;
   public static String bo;
   public static String bp;
   public static String bq;
   public static String br;
   public static String bs;
   public static String bt;
   public static String bu;
   public static String bv;
   public static String bw;
   public static String bx;
   public static String by;
   public static String bz;
   public static String bA;
   public static String bB;
   public static String bC;
   public static String bD;
   public static String bE;
   public static String bF;
   public static String bG;
   public static String bH;
   public static String bI;
   public static String bJ;
   public static String bK;
   public static String bL;
   public static String bM;
   public static String bN;
   public static String bO;
   public static String bP;
   public static String bQ;
   public static String bR;
   public static String bS;
   public static String bT;
   public static String bU;
   public static String bV;
   public static String bW;
   public static String bX;
   public static String bY;
   public static String bZ;
   public static String ca;
   public static String cb;
   public static String cc;
   public static String cd;
   public static String ce;
   public static String cf;
   public static String cg;
   public static String ch;
   public static String ci;
   public static String cj;
   public static String ck;
   public static String cl;
   public static String cm;
   public static String cn;
   public static String co;
   public static String cp;
   public static String cq;
   public static String cr;
   public static String cs;
   public static String ct;
   public static String cu;
   public static String cv;
   public static String cw;
   public static String cx;
   public static String cy;
   public static String cz;
   public static String cA;
   public static String cB;
   public static String cC;
   public static String cD;
   public static String cE;
   public static String cF;
   public static String cG;
   public static String cH;
   public static String cI;
   public static String cJ;
   public static String cK;
   public static String cL;
   public static String cM;
   public static String cN;
   public static String cO;
   public static String cP;
   public static String cQ;
   public static String cR;
   public static String cS;
   public static String cT;
   public static String cU;
   public static String cV;
   public static String cW;
   public static String cX;
   public static String cY;
   public static String cZ;
   public static String da;
   public static String db;
   public static String dc;
   public static String dd;
   public static String noFriend;
   public static String df;
   public static String dg;
   public static String dh;
   public static String di;
   public static String dj;
   public static String dk;
   public static String dl;
   public static String dm;
   public static String dn;
   public static String var_do;
   public static String dp;
   public static String dq;
   public static String dr;
   public static String ds;
   public static String dt;
   public static String du;
   public static String dv;
   public static String dw;
   public static String dx;
   public static String dy;
   public static String dz;
   public static String dA;
   public static String dB;
   public static String dC;
   public static String dD;
   public static String dE;
   public static String dF;
   public static String dG;
   public static String dH;
   public static String dI;
   public static String dJ;
   public static String dK;
   public static String dL;
   public static String dM;
   public static String dN;
   public static String dO;
   public static String dP;
   public static String dQ;
   public static String dR;
   public static String dS;
   public static String dT;
   public static String dU;
   public static String dV;
   public static String dW;
   public static String dX;
   public static String dY;
   public static String dZ;
   public static String ea;
   public static String eb;
   public static String ec;
   public static String ed;
   public static String ee;
   public static String ef;
   public static String eg;
   public static String eh;
   public static String ei;
   public static String[] ej;
   public static String[] nameCasino;
   public static String[] el;
   public static String[] em;
   public static String[] en;
   public static String[] eo;
   public static String[] ep;
   public static String[] eq;
   public static String[] er;
   public static String[] es;
   public static String[] et;
   public static String[] eu;
   public static String[] ev;
   public static String[] ew;
   public static String[] ex;
   public static String[] ey;
   public static String[] nameRegion;
   public static String[] nameMenuOn;
   public static String[] eB;
   public static String[] eC;
   public static String[] eD;
   private static String[] eR = new String[]{"/normal", "/medium", "/hd"};
   public static String[] eE;
   public static String[][] eF;
   public static String[][] eG;
   public static String[][] eH;
   public static String eI;
   public static String eJ;
   public static String eK;
   public static String eL;
   public static String eM;
   public static String eN;
   public static String eO;
   public static String eP;
   public static String eQ;

   public T() {
      b = "Xin chờ";
      c = "Menu";
      d = "Đóng";
      e = "Đồng ý";
      f = "Cập nhật";
      i = "Tìm bàn chơi";
      nameCasino = new String[]{"Tiến lên", "Phỏm", "Caro", "Cờ tướng", "Kim cương", "Bầu cua"};
      el = new String[]{"Kim cương", "Bầu cua", "Caro", "Cờ tướng", "Ongame"};
      String[] var10000 = new String[]{"Tiến lên", "Phỏm", "Caro", "Cờ tướng"};
      j = "Sẵn sàng";
      k = "Không s.sàng";
      n = "Bắt đầu";
      o = "Có";
      p = "Không";
      q = "Tin nhắn";
      r = "Đặt tiền cược";
      s = "Đặt số người";
      t = "Đặt mật khẩu";
      u = "Rời bàn";
      v = "Đuổi";
      w = "Tiếp tục";
      x = "Thoát";
      y = "Kết bạn";
      z = "OK";
      A = "Đánh";
      B = "Bỏ lượt";
      C = "xu";
      D = "lượng";
      E = "Lượng khóa";
      ej = new String[]{"2 người", "3 người", "4 người"};
      F = "Sắp bài xong";
      G = "Số tiền cược";
      H = "Bạn bị đuổi.";
      I = "Đã đặt mật khẩu.";
      J = "Đối thủ thoát. Bạn thắng";
      K = "Tới trắng";
      L = "Nhắn tin";
      M = "Đang kết nối";
      N = "Đang đăng nhập";
      O = "Chọn";
      P = "Bạn có muốn thoát?";
      Q = "Bạn có chắc bỏ lượt?";
      R = "Bắt buột đánh 3 bích trước.";
      S = "Không cùng loại hoặc nhỏ hơn bài đang trên bàn.";
      T = "$";
      U = " đi trước.";
      V = "Phòng ";
      W = "Tới ";
      em = new String[]{"Cấp độ chính: ", "Cấp độ nông trại: ", "Cấp độ", "Cấp độ câu cá: "};
      X = "Password:";
      Y = "Kết nối thất bại. Xin kiểm tra kết nối wifi/3g";
      Z = "Mua";
      aa = "Bạn bè";
      ab = "Cài đặt";
      ac = "ăn";
      ad = "Nhận";
      ae = "Hạ Phỏm";
      af = "Bạn chỉ được đánh một lá.";
      ag = "Bạn chưa chọn bài.";
      ah = "Nếu đánh lá này bạn sẽ phá phỏm";
      ai = "Chờ đến lượt.";
      aj = "Không đúng phỏm.";
      ak = "Bạn chọn quá nhiều bài.";
      al = "Không phải là phỏm.";
      am = "Xem thành tích";
      an = "Đến bàn số..";
      ao = "Tiền: ";
      ap = "Password:";
      aq = "vao";
      ay = "Số lượng: ";
      az = "Giá: ";
      aA = "Tên: ";
      aB = "Quần ";
      aC = "áo ";
      aD = "Tóc ";
      aE = "Mắt ";
      aF = "Bạn có muốn mua không?";
      ey = new String[]{"Nhảy", "Nằm", "Ngồi bệt", "Quỳ"};
      aG = "Bạn muốn mua bằng gì?";
      aJ = "TK Chính";
      aK = "Thu nhập: ";
      aL = "Đang lấy dữ liệu nông trại...";
      getData = "Đang cập nhật dữ liệu..";
      aN = "Kho hàng";
      ex = new String[]{"Phòng sơ cấp", "Phòng trung cấp", "Phòng cao thủ", "Phòng thi đấu"};
      aO = "Mất kết nối";
      aP = "Thắng";
      aQ = "Thua";
      aR = "Hòa";
      aS = "Bỏ cuộc";
      aT = "Đối thủ chưa sẵn sàng";
      aU = " đã thoát";
      eG = new String[][]{{"hiện", "ẩn", "Tên"}, {"hiện", "ẩn", "Chỉ đường"}, {"", "", "âm thanh"}, {"GPRS", "Wifi", "Kết nối"}, {"Tiếng việt", "Tiếng Anh", "Ngôn ngữ"}};
      aV = "Xong";
      aW = "Khu vực đã đầy.";
      aX = "Khu vực ";
      aY = "Lá bài bạn đánh không có thực.";
      aZ = "Năng ít nhất 2 lá để ăn.";
      ba = "Chat";
      bb = "Xóa";
      nameRegion = new String[]{"Khu nhà ở", "Khu sinh thái", "Sân bay", "Khu giải trí", "Khu mua sắm", "Công viên", "Khu ngoại ô", "Nông trại"};
      bc = "Đang vào ";
      bd = "Tưới nước";
      be = "Làm đất";
      bf = "Đã hết ";
      bg = "Bán";
      bh = "Bạn muốn phá cây đang có?";
      bi = "Bị tiêu chảy";
      bj = "Bị cúm";
      bk = "Đói bụng";
      bl = "Mệt quá";
      bm = "Sữa";
      bn = "Trứng";
      bo = "Không vào được nông trại.";
      bp = "Bạn có muốn bán";
      bq = " Giờ";
      br = "Giống";
      bs = "Vật Phẩm";
      bt = "Không thể vào.";
      bu = "Kho Giống";
      bv = "Bạn đã bị bắt.";
      bw = "Hết thức ăn.";
      bx = "Tiền bán nông sản: ";
      by = "Bản thân";
      bz = "Tiếp";
      bA = "Nhớ";
      dt = "Đăng ký";
      bB = "Quên mật khẩu";
      bC = "Tên tài khoản";
      bD = "Câu hỏi thường gặp";
      bE = "Cập nhật game";
      bF = "Hỗ trợ";
      bG = "Xóa bộ nhớ tạm";
      bH = "Đã";
      bI = "Bạn phải dùng số điện thoại đăng ký tài khoản để lấy mật khẩu.";
      bJ = "Bỏ";
      bK = "Không đồng ý";
      bL = "Xem điều khoản";
      bM = "Bạn phải chấp nhận điều khoản.";
      bN = "Tài khoản:";
      bO = "Mật khẩu";
      bP = "Chọn T. Phố";
      bQ = "Nhớ mật khẩu";
      bR = "Sự kiện";
      bS = "Tặng quà";
      bT = "Đánh";
      bU = "Hôn";
      bV = "Xem thông tin";
      bW = "Nhắn tin riêng";
      bX = "Hành động";
      bY = "Cảm xúc";
      bZ = "Giao dịch";
      ca = " tặng hoa rơi cho ";
      cb = " với ";
      cc = "Từ chối";
      eH = new String[][]{{"Số seri:", ""}, {"Mã số thẻ:", ""}};
      eu = new String[]{"C.Độ: ", "T.Thiện", "G.Rối", "S.Điệu", "V.Vẻ", "S.Khỏe"};
      cd = "Chỉ số";
      ce = "Hiện có: ";
      ev = new String[]{"Nạp tiền", "Chuyển tiền", "Bản thân"};
      ew = new String[]{"TK chính sang nông trại", "TK nông trại sang chính"};
      cf = "NẠP TIỀN";
      cg = "Tin đến";
      ch = "Đóng tab";
      ci = "Bắt đầu chat với ";
      cj = "Xong";
      ck = "Tạo nhân vật";
      et = new String[]{"Nam", "Nữ"};
      cl = "Tạo nhân vật không thành công.";
      cm = "Hủy";
      cn = "co the thu hoach";
      co = "Rương đồ";
      cp = "Bỏ món đồ này ?";
      es = new String[]{"Bỏ vào rương ?", "Sử dụng vật phẩm này ?", "Bỏ vào giỏ đồ ?", "Bỏ vào rương ?"};
      cq = "Di chuyển";
      cr = "Độ bền: ";
      cs = "Sử dụng";
      ct = "Đã gửi tin nhắn.";
      cu = "Không thể gửi tin nhắn.";
      cv = "Nếu thoát bạn sẽ bị xử thua. Bạn có muốn thoát?";
      ep = new String[]{"Nghe nhỏ", "Nghe vừa", "Nghe lớn"};
      eE = new String[]{"Cóc", "Sảnh", "Đôi", "Ba lá", "Ba đôi thông", "Bốn đôi thông", "Tứ quý"};
      eq = new String[]{"Chặt heo đen", "Chặt heo đỏ", "Chặt đôi heo đen", "Chặt đôi heo đỏ", "Chặt đôi heo 1 đen 1 đỏ", "Chặt 3 đôi thông", "Chặt tứ quý", "Chặt 4 đôi thông"};
      cw = "Thông tin";
      cx = "Đổi mật khẩu";
      eF = new String[][]{{"Mật khẩu", "Cũ"}, {"Mật khẩu", "Mới"}, {"Nhập lại", "Mật khẩu"}};
      cy = "Xong";
      er = new String[]{"Xin nhập mật khẩu hiện tại.", "Xin nhập mật khẩu mới.", "Xin nhập lại mật khẩu mới.", "Hai mật khẩu mới phải giống nhau.", "Mật khẩu mới phải khác mật khẩu cũ."};
      cz = "Quăng câu";
      cA = "Cắn câu";
      cB = "Trật rồi";
      cC = "Số cá câu được: ";
      cD = "Thành tích";
      eo = new String[]{"Bạn chưa nhập tên", "Bạn chưa nhập mật khẩu", "Bạn chưa nhập lại mật khẩu.", "Hai mật khẩu không giống nhau."};
      cE = "Nhập lại";
      var10000 = new String[]{"Hoa rơi", "Tim bay"};
      cF = "Tặng game cho..";
      cG = "Gui cho ban be";
      cH = "So dien thoai";
      cI = "Ban co the chon so dien thoai tu Menu / Danh ba";
      cJ = "Game khác";
      cK = "Bạn có muốn nâng cấp giỏ đồ không ?";
      cL = "Bạn có muốn thoát game để vào mục này không?";
      en = new String[]{"Bạn chưa nhập số seri.", "Bạn chưa nhập mã số thẻ."};
      cM = "ngày";
      cN = "Thức ăn";
      cO = "Quay số";
      cP = "Ban có muốn quay số món đồ này không ?";
      cQ = "Vĩnh viễn";
      cR = "Bạn muốn mua vật phẩm này với giá";
      cS = "Đặt";
      cT = "Chỉnh sửa nhà";
      cU = "Mua đồ";
      cV = "lát gạch, sơn tường";
      cW = "Chuyển, bán đồ";
      cX = "Không có vật phẩm ở đây";
      cY = "Di chuyển";
      cZ = "Xoay";
      da = "Bạn có muốn bán?";
      db = "Bạn không được đặt ở đây.";
      dc = "Đã có vật phẩm";
      dd = "Phải đặt sát tường.";
      noFriend = "Không có bạn trong khu này.";
      df = "Về nhà";
      dg = "Vào nhà bạn bè";
      dh = "cho";
      di = "tặng";
      dj = "Mời đến nhà";
      dk = "Nâng cấp giỏ đồ";
      dl = "Bạn bị chủ nhà đuổi.";
      dm = "Cháy";
      dn = "Ù";
      var_do = "Đền ù";
      dp = "Bạn được mời về nhà bởi ";
      dq = "Bạn có muốn không ?";
      dr = "Giỏ đồ";
      ds = "Không thể kết nối, xin kiểm tra lại GPRS/3G/Wifi.";
      du = " Để chọn ngôn ngữ vui lòng khởi động lại game.";
      dv = "Quay";
      nameMenuOn = new String[]{"Tiến Lên", "Phỏm", "Kim Cương", "Bầu Cua", "Chuyển tiền"};
      dw = "Quay về";
      l = "Đang mặc";
      dx = "C.độ yêu cầu: ";
      dy = "Quà";
      dz = "Xin chào ";
      dA = "Dừng";
      dC = "Bạn có muốn xem hướng dẫn chơi game không ?";
      dB = "Bạn có chắc muốn dừng hướng dẫn không?";
      m = "Nấu ăn";
      dD = "Đang nấu";
      ei = "Bạn có muốn hủy món đang nấu không?";
      eI = "Không đủ ";
      eJ = "Giá bán: ";
      eK = "Nguyên liệu: ";
      eL = "Hoàn thành";
      h = "Nấu ăn nhanh";
      eM = "Thời gian: ";
      eN = "Nâng cấp nhanh";
      g = "Nâng cấp";
      eO = "Thu hoạch";
      dE = "Tk game: ";
      a = "Quan hệ";
      dF = "Kho của bạn đã hết hạt giống, xin vào cửa hàng đễ mua.";
      dG = "Kho của bạn đã hết thuốc, xin vào cửa hàng đễ mua.";
      dH = "Bạn có muốn nâng cấp kho hàng không ?";
      dI = "Không có vật nuôi nào bị bệnh";
      dJ = "ô này không có cây.";
      dK = "ô này không có cây.";
      dL = "Hãy chọn ô không có cây hoặc cây đã chết.";
      dM = "Kho của bạn đã hết phân bón, xin vào cửa hàng đễ mua.";
      dN = "Lông";
      dO = "trom";
      dP = "Sản phẩm";
      dQ = "Sản lượng";
      dR = "Chăm sóc vật nuôi";
      dS = "Gieo hạt";
      dT = "Chăm sóc cây trồng";
      dU = "Trị bệnh";
      dV = "Kho của bạn đã hết thuốc tiêu chảy, xin vào cửa hàng đễ mua.";
      dW = "Kho của bạn đã hết thuốc cúm, xin vào cửa hàng đễ mua.";
      dX = "Cho ăn";
      dY = "Kho của bạn đã hết thức ăn, xin vào cửa hàng đễ mua.";
      dZ = "Thuốc bổ";
      ea = "Kho của bạn đã hết thuốc bổ, xin vào cửa hàng đễ mua.";
      eb = "Bạn có muốn bất đầu lể cưới không ?";
      eB = new String[]{"Lễ cưới của chú rể ", " và cô dâu ", " chính thức bắt đầu.  mời Cô Dâu và Chú rể cùng tiến về lễ đường."};
      eC = new String[]{"Hôm nay chúng ta có mặt tại đây để cùng chúc mừng cho đám cưới của chú rể ", "Vượt qua bao khó khăn thử thách bằng tình yêu vĩnh cửu, sau cùng cả hai đã đạt đến bến bờ hạnh phúc.", "Kể từ hôm nay, ta tuyên bố 2 bạn chính thức trở thành vợ chồng.", "Chú rể có thể hôn Cô Dâu."};
      ec = "Đặt cược";
      ed = "Lịch sử";
      eP = "Bạn có muốn thoát không ?";
      ee = "Bạn có muốn thoát không (nếu có đặt cược bạn sẽ mất tiền cược) ?";
      ef = "Bản đặt cược";
      eD = new String[]{"Thấp", "Thường", "Cao"};
      eg = "Tỉ lệ";
      eh = "Phong độ";
      eQ = "Sức khỏe";
   }

   public static String a() {
      return eR[Canvas.stypeInt];
   }

   public static String[][] b() {
      return new String[][]{{"Chào mừng bạn đến với avt.Avatar - Thành phố diệu kỳ", "Chúng ta sẽ dạo một vòng qua thành phố này nhé!", "Thành phố có rất nhiều khu, chúng ta sẽ đến từng khu để tìm hiểu", "Khu Giải Trí là nơi nào nhiệt nhất thành phố. Mời bạn chọn vào nào!"}, {"Nông Trại là nơi trồng trọt và chăn nuôi, bạn có thể tăng thêm thu nhập", "Bạn hãy chọn vào mục Nông Trại nào"}, {"Tiếp theo là khu Mua Sắm, nơi mà bạn có thể lựa chọn cho mình những bộ trang phục đẹp mắt.", "Chọn vào tham quan khu Mua Sắm ngay bạn nhé!"}, {"Tiếp theo là khu Sinh Thái, nơi mà bạn có thể thư giãn với việc câu cá", "Mời bạn chọn vào Khu Sinh Thái"}, {"Khu vực Công Viên là nơi bạn có thể gặp gỡ và trò chuyện với bạn bè", "Bạn có thể vào thử Công Viên. Sau khi dạo một vòng hãy đến Trạm Xe Buýt để trở lại nơi này nhé!"}, {"Thành phố diệu kỳ còn rất nhiều khu khác để bạn khám phá. Hãy ghé qua khu sân bay thường xuyên để cập nhật các địa điểm mới", "Giờ bạn có thể vào nông trại, vào hội cờ, đi mua sắm,đi câu cá, hoặc làm bất kỳ điều gì bạn thích. Cám ơn bạn đã xem hướng dẫn!"}};
   }

   public static String[][] getTextMapScr() {
      return new String[][]{{"Chào mừng bạn đến khu giải trí.", "Nơi đây gồm hội quán cờ, Tòa thị chính, Trường đua pet sôi động và các gian hàng quay số may mắn cùng với đấu giá ngược."}, {"Đây là tòa thị chính, nơi bạn có thể nhận những nhiệm vụ trong game và xin gia nhập vào các hội nhóm.", "Hãy di chuyển nhân vật đến tham quan tòa thị chính đi nào!"}, {"Đây là trường đua thú sôi động. Bạn có thể vào xem những trận đua thú vô cùng hấp dẫn.", "Hãy tham quan trường đua trước khi chúng ta di chuyển sang khu vực khác nhé!"}};
   }

   public static String[][] d() {
      return new String[][]{{"Chào mừng bạn đến khu mua sắm, tại đây bạn có thể thỏa thích lựa chọn cho mình những bộ thời trang đẹp mắt và cá tính.", "Đầu tiên mời bạn vào Shop tham quan. Hãy di chuyển nhân vật đến shop nào."}, {"Đây là nhà bán thú nuôi, nơi bạn có thể lựa chọn cho mình những chú pet thật xinh xắn.", "Hãy vào xem một chút nhé!"}, {"Bạn có thể vào thay đổi kiểu tóc và mắt của mình tại Thẩm Mỹ Viện.", "Hãy vào tham quan thử nhé!"}};
   }

   public static String[][] e() {
      return new String[][]{{"Hãy gặp thị trưởng để nhận nhiệm vụ và gặp NPC Hội Nhóm để xin gia nhập vào các hội nhóm."}};
   }

   public static String[][] getTextFarmPath() {
      return new String[][]{{"Khu vực nông trại có 4 nơi bạn có thể vào: Cửa hàng, ATM, Nông trại của mình, và Nông trại của bạn bè.", "Cửa hàng là nơi bạn mua hạt giống, vật nuôi và các vật phẩm khác", "Tại sao bạn lại không thử mua một ít hạt giống nhỉ?"}, {"Hiện tại trong người của bạn có sẵn vài hạt giống. Nhưng bạn vẫn có thể mua thêm hạt giống khác nếu thích.", "Hãy chọn mua thử nào!"}, {"Hãy chọn số lượng muốn mua", "Sau khi mua xong, bạn hãy chọn Đóng để rời khỏi cửa hàng"}, {"Chúng ta đã có một số hạt giống rồi!", "Hãy bước vào khu vực nông trại của bạn để bắt đầu gieo hạt!"}};
   }

   public static String[][] g() {
      return new String[][]{{"Đây là nông trại của bạn", "Chúng ta sẽ bắt đầu trải nghiệm làm một người nông dân chăm chỉ nhé!", "Bạn có thấy những ô đất không?", "Đây là khu vực bạn có thể trồng cây.", "Bắt đầu thôi nào! Bạn hãy di chuyển đến đó và chọn một ô đất", "Hãy chọn mục Làm Đất để xới đất nào!"}, {"Chúc mừng! Bạn đã hoàn thành xong việc làm đất", "Tiếp theo bạn hãy chọn hạt giống."}, {"Bạn đã gieo hạt. Trên mỗi ô đất có hiển thị thời gian bạn có thể thu hoạch được", "Bạn hãy thường xuyên vào tưới nước, bón phân cho cây cho đến khi thu hoạch nhé!"}, {"Đây là khu chăn nuôi gia súc.", "Bạn cần mua gia súc ngoài cửa hàng và thả nó vào đây", "hãy chăm sóc nó, cho ăn và tiêm thuốc bổ đều đặn, đến khi lớn bạn có thể thu hoạch sữa và trứng"}, {"Đây là nhà bếp, nơi bạn có thể nấu những món ăn từ nông sản bạn thu hoạch được."}, {"Đây là cây khế, cây khế sẽ cho thu hoạch trong thời gian nhất định.", "Hãy nâng cấp cây khế lên càng cao, sản lượng thu hoạch sẽ càng nhiều bạn nhé!"}, {"Bạn có thể nuôi cá trong ao này bằng cách mua cá từ cửa hàng bên ngoài", "Sau khi thu hoạch cây, vật nuôi, bạn sẽ có một khoản tiền nhỏ trong tài khoản nông trại", "Bạn có thể ra ATM để chuyển sang tài khoản chính để có thể dùng nhé!"}};
   }

   public static String[][] getTextShop() {
      return new String[][]{{"Chào mừng bạn đến với cửa hàng quần áo.", "Hãy bước đến gặp người bán hàng để thử quần áo, bạn nhớ chú ý giá cả nhé!"}, {"Sử dụng các mũi tên để chọn các bộ quần áo khác nhau", "Nếu bạn có đủ tiền, hãy chọn mua một bộ quần áo mới"}};
   }

   public static String[][] i() {
      return new String[][]{{"Chào mừng bạn đến với khu câu cá.", "Có 3 khu câu cá khác nhau, với 3 cấp độ khác nhau"}, {"Khu câu cá rô dành cho người mới tập câu"}, {"Khu câu cá lóc dành cho các bạn đã biết câu"}, {"Khu câu cá mập dành cho các bạn đã là cao thủ câu cá"}, {"Để có thể câu cá bạn phải mua cần câu, mồi câu, vé câu"}, {"Để có thể mua bạn có thể chat chữ cauca cửa hàng sẽ tự động hiện lên"}, {"Hoặc chat chữ banca nếu bạn muốn bán cá"}, {"Giờ chúng ta sẽ rời nơi này. Bạn có thể đến đây bất cứ khi nào bạn muốn!"}};
   }

   public static String[] j() {
      return new String[]{"Bạn có thể ra khỏi nơi này bằng cách đi đến nơi mũi tên chỉ"};
   }

   public static String k() {
      return MapScr.isNewVersion ? "xeng" : C;
   }

   public static String l() {
      return MapScr.isNewVersion ? "xèng" : C;
   }
}
