buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
        maven { url 'https://s01.oss.sonatype.org' }
    }
    dependencies {
        classpath "com.mobidevelop.robovm:robovm-gradle-plugin:$robovmVersion"
    }
}
apply plugin: 'java-library'
apply plugin: 'robovm'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

compileJava {
    options.encoding = 'UTF-8'
}

ext {
    mainClassName = "ios.IOSLauncher"
}


robovm {
    archs = 'arm64'
    iosSkipSigning = true
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build

dependencies {
    implementation "com.mobidevelop.robovm:robovm-cocoatouch:$robovmVersion"
    implementation "com.mobidevelop.robovm:robovm-rt:$robovmVersion"
    implementation project(':core')
}
