package avt;

import main.Canvas;

public final class T {
   public static String wedding;
   public static String pleaseWait;
   public static String menu;
   public static String close;
   public static String agree;
   public static String delete;
   public static String clearAll;
   public static String addAll;
   public static String updateList;
   public static String update;
   public static String playNow;
   public static String strongest;
   public static String ready;
   public static String richest;
   public static String wearing;
   public static String cook;
   public static String start;
   public static String yes;
   public static String no;
   public static String viewMessage;
   public static String setMoney;
   public static String setNumPlayers;
   public static String setPass;
   public static String exitBoard;
   public static String kick;
   public static String continuee;
   public static String exit;
   public static String addFriend;
   public static String OK;
   public static String fire;
   public static String skip;
   public static String xu;
   public static String gold;
   public static String noReady;
   public static String sapBaiXong;
   public static String numTienCuoc;
   public static String youAreKicked;
   public static String setPassed;
   public static String opponentQuit;
   public static String forceFinish;
   public static String sendMessage;
   public static String connecting;
   public static String logging;
   public static String selectt;
   public static String doYouWantExit2;
   public static String doYouWantSkip;
   public static String youMustFire3Bich;
   public static String notSameOrSmaller;
   public static String dola;
   public static String firstFire;
   public static String room;
   public static String goad;
   public static String ifPassword;
   public static String gameDraw;
   public static String buy;
   public static String friend;
   public static String option;
   public static String eat;
   public static String gett;
   public static String haPhom;
   public static String canYouOnceOnly;
   public static String yetSellectCard;
   public static String ifFireBreakPhom;
   public static String waitToCurrent;
   public static String notSamePhom;
   public static String youSelect;
   public static String notPhom;
   public static String viewMyInfo;
   public static String goToBoard;
   public static String moneyStr;
   public static String banChiCo;
   public static String aq = "vào";
   public static String ar = "/font.av";
   public static String as = "/bg.av";
   public static String at = "/home.av";
   public static String au = "/farm.av";
   public static String av = "/effect.av";
   public static String aw = "/main.av";
   public static String ax = "/dialLucky.av";
   public static String number;
   public static String priceStr;
   public static String nameStr;
   public static String pant;
   public static String setMaxMoney;
   public static String hair;
   public static String eye;
   public static String doYouWantBuy;
   public static String selectMoney;
   public static String aH = "http://";
   public static String aI = "@username";
   public static String youFirstFire;
   public static String inCome;
   public static String getFarmData;
   public static String enemyFirstFire;
   public static String storePro;
   public static String disConnect;
   public static String win;
   public static String lose;
   public static String draw;
   public static String give;
   public static String opponentAreNotReady;
   public static String exited;
   public static String complete;
   public static String areaIsFull;
   public static String area;
   public static String cardToMiss;
   public static String upTwoCard;
   public static String chat;
   public static String del;
   public static String beingOn;
   public static String watering;
   public static String land;
   public static String empty;
   public static String sell;
   public static String youWantBreakTree;
   public static String diarrhea;
   public static String flu;
   public static String hunger;
   public static String tire;
   public static String sixPointNoWin;
   public static String block2NoWin;
   public static String notOnFarm;
   public static String pw;
   public static String h;
   public static String seed;
   public static String item;
   public static String notOnFarmOther;
   public static String StoreSeed;
   public static String youAreBittenByDogByHound;
   public static String foodForEmpty;
   public static String moneySellPro;
   public static String mySeft;
   public static String next;
   public static String remem;
   public static String fogetPass;
   public static String nameAcc;
   public static String FAQs;
   public static String updateGame;
   public static String support;
   public static String delRMS;
   public static String alreadyDelRMS;
   public static String youUseNumRegGetpass;
   public static String removee;
   public static String connectFail;
   public static String cannotMove;
   public static String areYouAgreeRule;
   public static String chieuTuong;
   public static String pass;
   public static String cloth;
   public static String rememPass;
   public static String eventt;
   public static String giveGift;
   public static String hit;
   public static String kiss;
   public static String tkChinh;
   public static String tkFarm;
   public static String action;
   public static String feel;
   public static String exchange;
   public static String giveGiftFlower;
   public static String with;
   public static String refused;
   public static String index;
   public static String have;
   public static String loadMoney;
   public static String msgNew;
   public static String closeTab;
   public static String beginChat;
   public static String success;
   public static String createChar;
   public static String createCharFail;
   public static String cancel;
   public static String canHarvest;
   public static String container;
   public static String doYouWantDel;
   public static String trans;
   public static String doBen;
   public static String use;
   public static String sentMsg;
   public static String canNotSendMsg;
   public static String doYouWantExit;
   public static String viewInfo;
   public static String changePass;
   public static String finish;
   public static String toss;
   public static String bite;
   public static String miss;
   public static String numberFish;
   public static String achieve;
   public static String enterAgain;
   public static String giveGame;
   public static String sentToFriend;
   public static String phoneNumber;
   public static String youCanSelectFromMenu;
   public static String otherGame;
   public static String getData;
   public static String doYouWantExitIntoRegion;
   public static String day;
   public static String food;
   public static String dial;
   public static String doYouWantDial;
   public static String forever;
   public static String doYouWanBuyPrice;
   public static String sett;
   public static String homeRepait;
   public static String buyItem;
   public static String latGach;
   public static String sellItem;
   public static String noItem;
   public static String move;
   public static String rota;
   public static String doWantSellItem;
   public static String noPlaceItemHere;
   public static String haveItem;
   public static String setTuong;
   public static String noFriend;
   public static String goHome;
   public static String joinFrHome;
   public static String cho;
   public static String dunation;
   public static String inviteMyHouse;
   public static String won;
   public static String outHouse;
   public static String chay;
   public static String u;
   public static String denU;
   public static String youAreInvite;
   public static String doYouWant;
   public static String basket;
   public static String canNotConnect;
   public static String register;
   public static String uNeedExitGame;
   public static String Dial;
   public static String back;
   public static String youAreBittenByDog;
   public static String gift;
   public static String StoreEmtpy;
   public static String notTooGreedy;
   public static String usureStop;
   public static String milk;
   public static String cooking;
   public static String tkNew;
   public static String egg;
   public static String youWantBuyPro;
   public static String feedFor;
   public static String areYouUseNumReg;
   public static String disagree;
   public static String viewRule;
   public static String acc;
   public static String selectRegion;
   public static String privateMsg;
   public static String noQ;
   public static String doo;
   public static String detail;
   public static String face;
   public static String lvNotChange;
   public static String cap;
   public static String salonBeauty;
   public static String lvUse;
   public static String hasRob;
   public static String feeding;
   public static String info;
   public static String view;
   public static String doYouWantToTrade;
   public static String doYouWantUpgradeCoffer;
   public static String farmQuickCare;
   public static String farmCrop;
   public static String farmAnimal;
   public static String farmAutoCare;
   public static String farmAutoOpenLand;
   public static String farmAutoUpgrade;
   public static String farmAutoPond;
   public static String farmAutoAnimal;
   public static String farmAutoAll;
   public static String farmKitchen;
   public static String farmWarehouse;
   public static String farmShop;
   public static String farmLobby;
   public static String farmSwitchAccount;
   public static String farmLogout;
   public static String farmComChao;
   public static String farmExit;
   public static String farmHarvest;
   public static String farmSowSeed;
   public static String farmTillSoil;
   public static String farmFertilize;
   public static String farmPestWeed;
   public static String farmWatering;
   public static String farmSellAnimal;
   public static String farmCollectProduce;
   public static String farmPumpTonic;
   public static String farmCureDisease;
   public static String datCuoc;
   public static String sendTo;
   public static String theft;
   public static String upgradeChest;
   public static String cityIsOffLine;
   public static String youAre;
   public static String doUWantCancel;
   public static String[] numPlayer;
   public static String[] constructing;
   public static String[] roomList;
   public static String[] roomName;
   public static String[] enterCard;
   public static String[] nameReg;
   public static String[] lister;
   public static String[] chatHeo;
   public static String[] enterPass;
   public static String[] emptyRoom;
   public static String[] gender;
   public static String[] login;
   public static String[] strName;
   public static String[] strTransMoney;
   public static String[] roomLevelText;
   public static String[] actionStr;
   public static String[] nameRegion;
   public static String[] selectLanguage;
   public static String[] enterPassReferral;
   public static String[] registerSuccess;
   public static String[] cannotRegister;
   private static String[] hd = new String[]{"/normal", "/medium", "/hd"};
   public static String[] cardTypeName;
   public static String[][] gettingPrice;
   public static String[][] sms;
   public static String[][] sendSmgFinish;
   public static String notEnough;
   public static String salePrice;
   public static String material;
   public static String done;
   public static String time;
   public static String QuickUpgrade;
   public static String harvest;
   public static String notSendSmg;
   public static String email;
   public static String utilities;
   public static String autoDialMenu;
   public static String utilChangeZone;
   public static String utilChangeMap;
   public static String utilAutoChat;
   public static String utilAutoKiss;
   public static String utilAutoKissAskOn;
   public static String utilAutoKissAskOff;
   public static String utilAutoKissNoFocus;
   public static String utilAutoHit;
   public static String utilAutoGift;
   public static String utilAutoTroll;
   public static String utilAutoClick;
   public static String utilStatus;
   public static String utilAutoTrollCode;
   public static String utilAutoTrollLimit;
   public static String utilAutoTrollIntervalMs;
   public static String utilAutoTrollSaveSuccess;
   public static String utilAutoGiftGiftId;
   public static String utilAutoGiftLimit;
   public static String utilAutoGiftLimitHint;
   public static String utilAutoGiftIntervalMs;
   public static String utilAutoGiftPayBy;
   public static String utilAutoGiftPayByHint;
   public static String utilAutoGiftSaveSuccess;
   public static String utilAutoClickKeyCode;
   public static String utilAutoClickStartKey;
   public static String utilAutoClickIntervalMs;
   public static String utilAutoClickSettingsNote;
   public static String utilAutoClickKeyList;
   public static String utilAutoClickSaveSuccess;
   public static String utilAutoClickNotifyToggle;
   public static String utilAutoClickEnabledNotice;
   public static String utilAutoClickDisabledNotice;
   public static String utilSpeed;
   public static String utilGameRoom;
   public static String utilVietnameseIME;
   public static String utilStateOn;
   public static String utilStateOff;
   public static String utilAutoClickStub;
   public static String utilGameRoomHint;
   public static String utilSpeedInputPrompt;
   public static String utilAutoChatBreak;
   public static String utilAutoChatContent;
   public static String utilAutoChatGuide;
   public static String utilAutoChatEnterContent;
   public static String utilAutoChatBack;
   public static String utilAutoChatSave;
   public static String utilAutoChatSaveSuccess;
   public static String utilAutoChatBreakPrompt;
   public static String utilAutoChatGuideBody;
   public static String utilMapSubSun;
   public static String utilMapSubGreenPark;
   public static String utilMapSubShop;
   public static String utilMapSubFun;
   public static String utilMapSubEco;
   public static String utilMapSubFarm;
   public static String utilStopAutoDial;
   public static String menuAuto;
   public static String menuAutoFishing;
   public static String menuAutoMining;
   public static String menuAutoFishingOn;
   public static String menuAutoFishingOff;
   public static String menuAutoFishingSettings;

   public T() {
      pleaseWait = "Xin chờ";
      menu = "Menu";
      close = "Đóng";
      agree = "Đồng ý";
      delete = "Xóa";
      clearAll = "Xóa tất cả";
      addAll = "Thêm tất cả";
      updateList = "Cập nhật";
      strongest = "Tìm bàn chơi";
      constructing = new String[]{"Tiến lên", "Phỏm", "Caro", "Cờ tướng", "Kim cương", "Bầu cua"};
      roomList = new String[]{"Kim cương", "Bầu cua", "Caro", "Cờ tướng", "Ongame"};
      String[] var10000 = new String[]{"Tiến lên", "Phỏm", "Caro", "Cờ tướng"};
      ready = "Sẵn sàng";
      richest = "Không s.sàng";
      start = "Bắt đầu";
      yes = "Có";
      no = "Không";
      viewMessage = "Tin nhắn";
      setMoney = "Đặt tiền cược";
      setNumPlayers = "Đặt số người";
      setPass = "Đặt mật khẩu";
      exitBoard = "Rời bàn";
      kick = "Đuổi";
      continuee = "Tiếp tục";
      exit = "Thoát";
      addFriend = "Kết bạn";
      OK = "OK";
      fire = "Đánh";
      skip = "Bỏ lượt";
      xu = "xu";
      gold = "lượng";
      noReady = "Lượng khóa";
      numPlayer = new String[]{"2 người", "3 người", "4 người"};
      sapBaiXong = "Sắp bài xong";
      numTienCuoc = "Số tiền cược";
      youAreKicked = "Bạn bị đuổi.";
      setPassed = "Đã đặt mật khẩu.";
      opponentQuit = "Đối thủ thoát. Bạn thắng";
      forceFinish = "Tới trắng";
      sendMessage = "Nhắn tin";
      connecting = "Đang kết nối";
      logging = "Đang đăng nhập";
      selectt = "Chọn";
      doYouWantExit2 = "Bạn có muốn thoát?";
      doYouWantSkip = "Bạn có chắc bỏ lượt?";
      youMustFire3Bich = "Bắt buột đánh 3 bích trước.";
      notSameOrSmaller = "Không cùng loại hoặc nhỏ hơn bài đang trên bàn.";
      dola = "$";
      firstFire = " đi trước.";
      room = "Phòng ";
      goad = "Tới ";
      roomName = new String[]{"Cấp độ chính: ", "Cấp độ nông trại: ", "Cấp độ", "Cấp độ câu cá: "};
      ifPassword = "Password:";
      gameDraw = "Kết nối thất bại. Xin kiểm tra kết nối wifi/3g";
      buy = "Mua";
      friend = "Bạn bè";
      option = "Cài đặt";
      eat = "ăn";
      gett = "Nhận";
      haPhom = "Hạ Phỏm";
      canYouOnceOnly = "Bạn chỉ được đánh một lá.";
      yetSellectCard = "Bạn chưa chọn bài.";
      ifFireBreakPhom = "Nếu đánh lá này bạn sẽ phá phỏm";
      waitToCurrent = "Chờ đến lượt.";
      notSamePhom = "Không đúng phỏm.";
      youSelect = "Bạn chọn quá nhiều bài.";
      notPhom = "Không phải là phỏm.";
      viewMyInfo = "Xem thành tích";
      goToBoard = "Đến bàn số..";
      moneyStr = "Tiền: ";
      banChiCo = "Password:";
      aq = "vao";
      number = "Số lượng: ";
      priceStr = "Giá: ";
      nameStr = "Tên: ";
      pant = "Quần ";
      setMaxMoney = "áo ";
      hair = "Tóc ";
      eye = "Mắt ";
      doYouWantBuy = "Bạn có muốn mua không?";
      actionStr = new String[]{"Nhảy", "Nằm", "Ngồi bệt", "Quỳ"};
      selectMoney = "Bạn muốn mua bằng gì?";
      youFirstFire = "TK Chính";
      inCome = "Thu nhập: ";
      getFarmData = "Đang lấy dữ liệu nông trại...";
      enemyFirstFire = "Đang cập nhật dữ liệu..";
      storePro = "Kho hàng";
      roomLevelText = new String[]{"Phòng sơ cấp", "Phòng trung cấp", "Phòng cao thủ", "Phòng thi đấu"};
      disConnect = "Mất kết nối";
      win = "Thắng";
      lose = "Thua";
      draw = "Hòa";
      give = "Bỏ cuộc";
      opponentAreNotReady = "Đối thủ chưa sẵn sàng";
      exited = " đã thoát";
      sms = new String[][]{{"hiện", "ẩn", "Tên"}, {"hiện", "ẩn", "Chỉ đường"}, {"", "", "âm thanh"}, {"GPRS", "Wifi", "Kết nối"}, {"Tiếng việt", "Tiếng Anh", "Ngôn ngữ"}};
      complete = "Xong";
      areaIsFull = "Khu vực đã đầy.";
      area = "Khu vực ";
      cardToMiss = "Lá bài bạn đánh không có thực.";
      upTwoCard = "Năng ít nhất 2 lá để ăn.";
      chat = "Chat";
      del = "Xóa";
      nameRegion = new String[]{"Khu nhà ở", "Khu sinh thái", "Sân bay", "Khu giải trí", "Khu mua sắm", "Công viên", "Khu ngoại ô", "Nông trại"};
      beingOn = "Đang vào ";
      watering = "Tưới nước";
      land = "Làm đất";
      empty = "Đã hết ";
      sell = "Bán";
      youWantBreakTree = "Bạn muốn phá cây đang có?";
      diarrhea = "Bị tiêu chảy";
      flu = "Bị cúm";
      hunger = "Đói bụng";
      tire = "Mệt quá";
      sixPointNoWin = "Sữa";
      block2NoWin = "Trứng";
      notOnFarm = "Không vào được nông trại.";
      pw = "Bạn có muốn bán";
      h = " Giờ";
      seed = "Giống";
      item = "Vật Phẩm";
      notOnFarmOther = "Không thể vào.";
      StoreSeed = "Kho Giống";
      youAreBittenByDogByHound = "Bạn đã bị bắt.";
      foodForEmpty = "Hết thức ăn.";
      moneySellPro = "Tiền bán nông sản: ";
      mySeft = "Bản thân";
      next = "Tiếp";
      remem = "Nhớ";
      register = "Đăng ký";
      fogetPass = "Quên mật khẩu";
      nameAcc = "Tên tài khoản";
      FAQs = "Câu hỏi thường gặp";
      updateGame = "Cập nhật game";
      support = "Hỗ trợ";
      delRMS = "Xóa bộ nhớ tạm";
      alreadyDelRMS = "Đã";
      youUseNumRegGetpass = "Bạn phải dùng số điện thoại đăng ký tài khoản để lấy mật khẩu.";
      removee = "Bỏ";
      connectFail = "Không đồng ý";
      cannotMove = "Xem điều khoản";
      areYouAgreeRule = "Bạn phải chấp nhận điều khoản.";
      chieuTuong = "Tài khoản:";
      pass = "Mật khẩu";
      cloth = "Chọn T. Phố";
      rememPass = "Nhớ mật khẩu";
      eventt = "Sự kiện";
      giveGift = "Tặng quà";
      hit = "Đánh";
      kiss = "Hôn";
      tkChinh = "Xem thông tin";
      tkFarm = "Nhắn tin riêng";
      action = "Hành động";
      feel = "Cảm xúc";
      exchange = "Giao dịch";
      giveGiftFlower = " tặng hoa rơi cho ";
      with = " với ";
      refused = "Từ chối";
      sendSmgFinish = new String[][]{{"Số seri:", ""}, {"Mã số thẻ:", ""}};
      login = new String[]{"C.Độ: ", "T.Thiện", "G.Rối", "S.Điệu", "V.Vẻ", "S.Khỏe"};
      index = "Chỉ số";
      have = "Hiện có: ";
      strName = new String[]{"Nạp tiền", "Chuyển tiền", "Bản thân"};
      strTransMoney = new String[]{"TK chính sang nông trại", "TK nông trại sang chính"};
      loadMoney = "NẠP TIỀN";
      msgNew = "Tin đến";
      closeTab = "Đóng tab";
      beginChat = "Bắt đầu chat với ";
      success = "Xong";
      createChar = "Tạo nhân vật";
      gender = new String[]{"Nam", "Nữ"};
      createCharFail = "Tạo nhân vật không thành công.";
      cancel = "Hủy";
      canHarvest = "co the thu hoach";
      container = "Rương đồ";
      doYouWantDel = "Bỏ món đồ này ?";
      emptyRoom = new String[]{"Bỏ vào rương ?", "Sử dụng vật phẩm này ?", "Bỏ vào giỏ đồ ?", "Bỏ vào rương ?"};
      trans = "Di chuyển";
      doBen = "Độ bền: ";
      use = "Sử dụng";
      sentMsg = "Đã gửi tin nhắn.";
      canNotSendMsg = "Không thể gửi tin nhắn.";
      doYouWantExit = "Nếu thoát bạn sẽ bị xử thua. Bạn có muốn thoát?";
      lister = new String[]{"Nghe nhỏ", "Nghe vừa", "Nghe lớn"};
      cardTypeName = new String[]{"Cóc", "Sảnh", "Đôi", "Ba lá", "Ba đôi thông", "Bốn đôi thông", "Tứ quý"};
      chatHeo = new String[]{"Chặt heo đen", "Chặt heo đỏ", "Chặt đôi heo đen", "Chặt đôi heo đỏ", "Chặt đôi heo 1 đen 1 đỏ", "Chặt 3 đôi thông", "Chặt tứ quý", "Chặt 4 đôi thông"};
      viewInfo = "Thông tin";
      changePass = "Đổi mật khẩu";
      gettingPrice = new String[][]{{"Mật khẩu", "Cũ"}, {"Mật khẩu", "Mới"}, {"Nhập lại", "Mật khẩu"}};
      finish = "Xong";
      enterPass = new String[]{"Xin nhập mật khẩu hiện tại.", "Xin nhập mật khẩu mới.", "Xin nhập lại mật khẩu mới.", "Hai mật khẩu mới phải giống nhau.", "Mật khẩu mới phải khác mật khẩu cũ."};
      toss = "Quăng câu";
      bite = "Cắn câu";
      miss = "Trật rồi";
      numberFish = "Số cá câu được: ";
      achieve = "Thành tích";
      nameReg = new String[]{"Bạn chưa nhập tên", "Bạn chưa nhập mật khẩu", "Bạn chưa nhập lại mật khẩu.", "Hai mật khẩu không giống nhau."};
      enterAgain = "Nhập lại";
      var10000 = new String[]{"Hoa rơi", "Tim bay"};
      giveGame = "Tặng game cho..";
      sentToFriend = "Gui cho ban be";
      phoneNumber = "So dien thoai";
      youCanSelectFromMenu = "Ban co the chon so dien thoai tu Menu / Danh ba";
      otherGame = "Game khác";
      getData = "Bạn có muốn nâng cấp giỏ đồ không ?";
      doYouWantExitIntoRegion = "Bạn có muốn thoát game để vào mục này không?";
      enterCard = new String[]{"Bạn chưa nhập số seri.", "Bạn chưa nhập mã số thẻ."};
      day = "ngày";
      food = "Thức ăn";
      dial = "Quay số";
      doYouWantDial = "Ban có muốn quay số món đồ này không ?";
      forever = "Vĩnh viễn";
      doYouWanBuyPrice = "Bạn muốn mua vật phẩm này với giá";
      sett = "Đặt";
      homeRepait = "Chỉnh sửa nhà";
      buyItem = "Mua đồ";
      latGach = "lát gạch, sơn tường";
      sellItem = "Chuyển, bán đồ";
      noItem = "Không có vật phẩm ở đây";
      move = "Di chuyển";
      rota = "Xoay";
      doWantSellItem = "Bạn có muốn bán?";
      noPlaceItemHere = "Bạn không được đặt ở đây.";
      haveItem = "Đã có vật phẩm";
      setTuong = "Phải đặt sát tường.";
      noFriend = "Không có bạn trong khu này.";
      goHome = "Về nhà";
      joinFrHome = "Vào nhà bạn bè";
      cho = "cho";
      dunation = "tặng";
      inviteMyHouse = "Mời đến nhà";
      won = "Nâng cấp giỏ đồ";
      outHouse = "Bạn bị chủ nhà đuổi.";
      chay = "Cháy";
      u = "Ù";
      denU = "Đền ù";
      youAreInvite = "Bạn được mời về nhà bởi ";
      doYouWant = "Bạn có muốn không ?";
      basket = "Giỏ đồ";
      canNotConnect = "Không thể kết nối, xin kiểm tra lại GPRS/3G/Wifi.";
      uNeedExitGame = " Để chọn ngôn ngữ vui lòng khởi động lại game.";
      Dial = "Quay";
      selectLanguage = new String[]{"Tiến Lên", "Phỏm", "Kim Cương", "Bầu Cua", "Chuyển tiền"};
      back = "Quay về";
      wearing = "Đang mặc";
      youAreBittenByDog = "C.độ yêu cầu: ";
      gift = "Quà";
      StoreEmtpy = "Xin chào ";
      notTooGreedy = "Dừng";
      milk = "Bạn có muốn xem hướng dẫn chơi game không ?";
      usureStop = "Bạn có chắc muốn dừng hướng dẫn không?";
      cook = "Nấu ăn";
      cooking = "Đang nấu";
      doUWantCancel = "Bạn có muốn hủy món đang nấu không?";
      notEnough = "Không đủ ";
      salePrice = "Giá bán: ";
      material = "Nguyên liệu: ";
      done = "Hoàn thành";
      playNow = "Nấu ăn nhanh";
      time = "Thời gian: ";
      QuickUpgrade = "Nâng cấp nhanh";
      update = "Nâng cấp";
      harvest = "Thu hoạch";
      tkNew = "Tk game: ";
      wedding = "Quan hệ";
      egg = "Kho của bạn đã hết hạt giống, xin vào cửa hàng đễ mua.";
      youWantBuyPro = "Kho của bạn đã hết thuốc, xin vào cửa hàng đễ mua.";
      feedFor = "Bạn có muốn nâng cấp kho hàng không ?";
      areYouUseNumReg = "Không có vật nuôi nào bị bệnh";
      disagree = "ô này không có cây.";
      viewRule = "ô này không có cây.";
      acc = "Hãy chọn ô không có cây hoặc cây đã chết.";
      selectRegion = "Kho của bạn đã hết phân bón, xin vào cửa hàng đễ mua.";
      privateMsg = "Lông";
      noQ = "trom";
      doo = "Sản phẩm";
      detail = "Sản lượng";
      face = "Chăm sóc vật nuôi";
      lvNotChange = "Gieo hạt";
      cap = "Chăm sóc cây trồng";
      farmQuickCare = "Chăm sóc nhanh";
      farmCrop = "Cây trồng";
      farmAnimal = "Vật nuôi";
      farmAutoCare = "Chăm sóc tự động";
      farmAutoOpenLand = "Auto nâng đất";
      farmAutoUpgrade = "Auto nâng hồ cá";
      farmAutoPond = "Auto nâng vật nuôi";
      farmAutoAnimal = "Auto nâng tất cả";
      farmAutoAll = "Auto Nâng nông trại";
      farmKitchen = "Nhà bếp";
      farmWarehouse = "Kho hàng";
      farmShop = "Cửa hàng";
      farmLobby = "Sảnh nông trại";
      farmSwitchAccount = "Chuyển tài khoản";
      farmLogout = "Đăng xuất";
      farmComChao = "Cơm cháo";
      farmExit = "Thoát";
      farmHarvest = "Thu hoạch";
      farmSowSeed = "Gieo hạt";
      farmTillSoil = "Làm đất";
      farmFertilize = "Bón phân";
      farmPestWeed = "Diệt sâu cỏ";
      farmWatering = "Tưới nước";
      farmSellAnimal = "Bá vật nuôi";
      farmCollectProduce = "Thu nông phẩm";
      farmPumpTonic = "Bơm thuốc bổ";
      farmCureDisease = "Chữa bệnh";
      salonBeauty = "Trị bệnh";
      lvUse = "Kho của bạn đã hết thuốc tiêu chảy, xin vào cửa hàng đễ mua.";
      hasRob = "Kho của bạn đã hết thuốc cúm, xin vào cửa hàng đễ mua.";
      feeding = "Cho ăn";
      info = "Kho của bạn đã hết thức ăn, xin vào cửa hàng đễ mua.";
      view = "Thuốc bổ";
      doYouWantToTrade = "Kho của bạn đã hết thuốc bổ, xin vào cửa hàng đễ mua.";
      doYouWantUpgradeCoffer = "Bạn có muốn bất đầu lể cưới không ?";
      enterPassReferral = new String[]{"Lễ cưới của chú rể ", " và cô dâu ", " chính thức bắt đầu.  mời Cô Dâu và Chú rể cùng tiến về lễ đường."};
      registerSuccess = new String[]{"Hôm nay chúng ta có mặt tại đây để cùng chúc mừng cho đám cưới của chú rể ", "Vượt qua bao khó khăn thử thách bằng tình yêu vĩnh cửu, sau cùng cả hai đã đạt đến bến bờ hạnh phúc.", "Kể từ hôm nay, ta tuyên bố 2 bạn chính thức trở thành vợ chồng.", "Chú rể có thể hôn Cô Dâu."};
      datCuoc = "Đặt cược";
      sendTo = "Lịch sử";
      notSendSmg = "Bạn có muốn thoát không ?";
      theft = "Bạn có muốn thoát không (nếu có đặt cược bạn sẽ mất tiền cược) ?";
      upgradeChest = "Bản đặt cược";
      cannotRegister = new String[]{"Thấp", "Thường", "Cao"};
      cityIsOffLine = "Tỉ lệ";
      youAre = "Phong độ";
      email = "Sức khỏe";
      utilities = "Tiện ích";
      autoDialMenu = "Auto quay số";
      utilChangeZone = "Chuyển khu";
      utilChangeMap = "Chuyển map";
      utilAutoChat = "Auto chat";
      utilAutoKiss = "Auto kiss";
      utilAutoKissAskOn = "Để dùng Auto kiss, bạn cần chỉ vào người đó trước.?";
      utilAutoKissAskOff = "Tắt Auto kiss không?";
      utilAutoKissNoFocus = "Chưa chỉ vào người chơi. Hãy chọn người trên map rồi bật lại.";
      utilAutoHit = "Auto đánh";
      utilAutoGift = "Auto tặng quà";
      utilAutoTroll = "Auto troll";
      utilAutoClick = "Auto click";
      utilStatus = "Trạng thái";
      utilAutoTrollCode = "Mã";
      utilAutoTrollLimit = "Số lần(0 tức là không giới hạn)";
      utilAutoTrollIntervalMs = "Quãng nghỉ(ms)";
      utilAutoTrollSaveSuccess = "Đã lưu cài đặt auto troll.";
      utilAutoGiftGiftId = "ID quà tặng:";
      utilAutoGiftLimit = "Số lần(0 tức là không giới hạn)";
      utilAutoGiftLimitHint = "0: tắt giới hạn (lặp vô hạn)";
      utilAutoGiftIntervalMs = "Quãng nghỉ(mili giây):";
      utilAutoGiftPayBy = "Tặng bằng:";
      utilAutoGiftPayByHint = "1: xu 2: lượng";
      utilAutoGiftSaveSuccess = "Đã lưu cài đặt auto tặng quà.";
      utilAutoClickKeyCode = "Mã phím";
      utilAutoClickStartKey = "Phím khởi động";
      utilAutoClickIntervalMs = "Quãng nghỉ(ms)";
      utilAutoClickSettingsNote = "Bảng mã (nhập số vào Mã phím):";
      utilAutoClickKeyList = "Phím chọn giữa [OK]: -5\nPhím gọi: -10\nPhím chọn trái: -6\nPhím chọn phải: -7\nPhím chuyển lên: -1\nPhím chuyển xuống: -2\nPhím chuyển trái: -3\nPhím chuyển phải: -4\nPhím số 1: 49 | 2: 50 | 3: 51 | 4: 52 | 5: 53\nPhím số 6: 54 | 7: 55 | 8: 56 | 9: 57 | 0: 48\nPhím sao (*): 42 | Phím #: 35";
      utilAutoClickSaveSuccess = "Đã lưu cài đặt auto click.";
      utilAutoClickNotifyToggle = "Thông báo bật/tắt auto:";
      utilAutoClickEnabledNotice = "Đã bật auto click";
      utilAutoClickDisabledNotice = "Đã tắt auto click";
      utilSpeed = "Tốc độ";
      utilGameRoom = "Phòng game";
      utilVietnameseIME = "Gõ tiếng Việt";
      utilStateOn = "Bật";
      utilStateOff = "Tắt";
      utilAutoClickStub = "Auto click: chưa hỗ trợ trên máy này.";
      utilGameRoomHint = "Vào khu giải trí / NPC để mở phòng chơi.";
      utilSpeedInputPrompt = "Nhập tốc độ 1-100. Số càng nhỏ tốc độ càng nhanh.";
      utilAutoChatBreak = "Quãng nghỉ";
      utilAutoChatContent = "Cài đặt nội dung";
      utilAutoChatGuide = "Hướng dẫn sử dụng";
      utilAutoChatEnterContent = "Nhập nội dung";
      utilAutoChatBack = "Quay lại";
      utilAutoChatSave = "Lưu";
      utilAutoChatSaveSuccess = "Lưu nội dung chat thành công.";
      utilAutoChatBreakPrompt = "Nhập quãng nghỉ (giây) 1-120. Ví dụ 3 = mỗi 3 giây gửi một đoạn.";
      utilAutoChatGuideBody = "Tách nhiều câu bằng dấu /, game gửi luân phiên từng đoạn theo quãng nghỉ (giây), lặp vô hạn cho đến khi tắt. Ví dụ iuem/nvl gửi iu em, rồi vl, rồi lặp lại. Một đoạn không có / thì gửi lặp câu đó.";
      utilMapSubSun = "Khu mặt trời";
      utilMapSubGreenPark = "Công viên";
      utilMapSubShop = "Khu mua sắm";
      utilMapSubFun = "Khu giải trí";
      utilMapSubEco = "Khu sinh thái";
      utilMapSubFarm = "Sảnh nông trại";
      utilStopAutoDial = "Tắt auto quay số";
      menuAuto = "Menu Auto";
      menuAutoFishing = "Auto câu cá";
      menuAutoMining = "Auto đào đá";
      menuAutoFishingOn = "Bật auto";
      menuAutoFishingOff = "Tắt auto";
      menuAutoFishingSettings = "Cài đặt";
   }

   public static String getPath() {
      return hd[Canvas.stypeInt];
   }

   public static String[][] getTextMiniMap() {
      return new String[][]{{"Chào mừng bạn đến với Avatar - Thành phố Tu", "Chúng ta sẽ dạo một vòng qua thành phố này nhé!", "Thành phố có rất nhiều khu, chúng ta sẽ đến từng khu để tìm hiểu", "Khu Giải Trí là nơi nào nhiệt nhất thành phố. Mời bạn chọn vào nào!"}, {"Nông Trại là nơi trồng trọt và chăn nuôi, bạn có thể tăng thêm thu nhập", "Bạn hãy chọn vào mục Nông Trại nào"}, {"Tiếp theo là khu Mua Sắm, nơi mà bạn có thể lựa chọn cho mình những bộ trang phục đẹp mắt.", "Chọn vào tham quan khu Mua Sắm ngay bạn nhé!"}, {"Tiếp theo là khu Sinh Thái, nơi mà bạn có thể thư giãn với việc câu cá", "Mời bạn chọn vào Khu Sinh Thái"}, {"Khu vực Công Viên là nơi bạn có thể gặp gỡ và trò chuyện với bạn bè", "Bạn có thể vào thử Công Viên. Sau khi dạo một vòng hãy đến Trạm Xe Buýt để trở lại nơi này nhé!"}, {"Thành phố diệu kỳ còn rất nhiều khu khác để bạn khám phá. Hãy ghé qua khu sân bay thường xuyên để cập nhật các địa điểm mới", "Giờ bạn có thể vào nông trại, vào hội cờ, đi mua sắm,đi câu cá, hoặc làm bất kỳ điều gì bạn thích. Cám ơn bạn đã xem hướng dẫn!"}};
   }

   public static String[][] getTextMapScr() {
      return new String[][]{{"Chào mừng bạn đến khu giải trí.", "Nơi đây gồm hội quán cờ, Tòa thị chính, Trường đua pet sôi động và các gian hàng quay số may mắn cùng với đấu giá ngược."}, {"Đây là tòa thị chính, nơi bạn có thể nhận những nhiệm vụ trong game và xin gia nhập vào các hội nhóm.", "Hãy di chuyển nhân vật đến tham quan tòa thị chính đi nào!"}, {"Đây là trường đua thú sôi động. Bạn có thể vào xem những trận đua thú vô cùng hấp dẫn.", "Hãy tham quan trường đua trước khi chúng ta di chuyển sang khu vực khác nhé!"}};
   }

   public static String[][] getTextMuaSam() {
      return new String[][]{{"Chào mừng bạn đến khu mua sắm, tại đây bạn có thể thỏa thích lựa chọn cho mình những bộ thời trang đẹp mắt và cá tính.", "Đầu tiên mời bạn vào Shop tham quan. Hãy di chuyển nhân vật đến shop nào."}, {"Đây là nhà bán thú nuôi, nơi bạn có thể lựa chọn cho mình những chú pet thật xinh xắn.", "Hãy vào xem một chút nhé!"}, {"Bạn có thể vào thay đổi kiểu tóc và mắt của mình tại Thẩm Mỹ Viện.", "Hãy vào tham quan thử nhé!"}};
   }

   public static String[][] getTextToaThiChinh() {
      return new String[][]{{"Hãy gặp thị trưởng để nhận nhiệm vụ và gặp NPC Hội Nhóm để xin gia nhập vào các hội nhóm."}};
   }

   public static String[][] getTextFarmPath() {
      return new String[][]{{"Khu vực nông trại có 4 nơi bạn có thể vào: Cửa hàng, ATM, Nông trại của mình, và Nông trại của bạn bè.", "Cửa hàng là nơi bạn mua hạt giống, vật nuôi và các vật phẩm khác", "Tại sao bạn lại không thử mua một ít hạt giống nhỉ?"}, {"Hiện tại trong người của bạn có sẵn vài hạt giống. Nhưng bạn vẫn có thể mua thêm hạt giống khác nếu thích.", "Hãy chọn mua thử nào!"}, {"Hãy chọn số lượng muốn mua", "Sau khi mua xong, bạn hãy chọn Đóng để rời khỏi cửa hàng"}, {"Chúng ta đã có một số hạt giống rồi!", "Hãy bước vào khu vực nông trại của bạn để bắt đầu gieo hạt!"}};
   }

   public static String[][] getTextFarm() {
      return new String[][]{{"Đây là nông trại của bạn", "Chúng ta sẽ bắt đầu trải nghiệm làm một người nông dân chăm chỉ nhé!", "Bạn có thấy những ô đất không?", "Đây là khu vực bạn có thể trồng cây.", "Bắt đầu thôi nào! Bạn hãy di chuyển đến đó và chọn một ô đất", "Hãy chọn mục Làm Đất để xới đất nào!"}, {"Chúc mừng! Bạn đã hoàn thành xong việc làm đất", "Tiếp theo bạn hãy chọn hạt giống."}, {"Bạn đã gieo hạt. Trên mỗi ô đất có hiển thị thời gian bạn có thể thu hoạch được", "Bạn hãy thường xuyên vào tưới nước, bón phân cho cây cho đến khi thu hoạch nhé!"}, {"Đây là khu chăn nuôi gia súc.", "Bạn cần mua gia súc ngoài cửa hàng và thả nó vào đây", "hãy chăm sóc nó, cho ăn và tiêm thuốc bổ đều đặn, đến khi lớn bạn có thể thu hoạch sữa và trứng"}, {"Đây là nhà bếp, nơi bạn có thể nấu những món ăn từ nông sản bạn thu hoạch được."}, {"Đây là cây khế, cây khế sẽ cho thu hoạch trong thời gian nhất định.", "Hãy nâng cấp cây khế lên càng cao, sản lượng thu hoạch sẽ càng nhiều bạn nhé!"}, {"Bạn có thể nuôi cá trong ao này bằng cách mua cá từ cửa hàng bên ngoài", "Sau khi thu hoạch cây, vật nuôi, bạn sẽ có một khoản tiền nhỏ trong tài khoản nông trại", "Bạn có thể ra ATM để chuyển sang tài khoản chính để có thể dùng nhé!"}};
   }

   public static String[][] getTextShop() {
      return new String[][]{{"Chào mừng bạn đến với cửa hàng quần áo.", "Hãy bước đến gặp người bán hàng để thử quần áo, bạn nhớ chú ý giá cả nhé!"}, {"Sử dụng các mũi tên để chọn các bộ quần áo khác nhau", "Nếu bạn có đủ tiền, hãy chọn mua một bộ quần áo mới"}};
   }

   public static String[][] getTextFish() {
      return new String[][]{{"Chào mừng bạn đến với khu câu cá.", "Có 3 khu câu cá khác nhau, với 3 cấp độ khác nhau"}, {"Khu câu cá rô dành cho người mới tập câu"}, {"Khu câu cá lóc dành cho các bạn đã biết câu"}, {"Khu câu cá mập dành cho các bạn đã là cao thủ câu cá"}, {"Để có thể câu cá bạn phải mua cần câu, mồi câu, vé câu"}, {"Để có thể mua bạn có thể chat chữ cauca cửa hàng sẽ tự động hiện lên"}, {"Hoặc chat chữ banca nếu bạn muốn bán cá"}, {"Giờ chúng ta sẽ rời nơi này. Bạn có thể đến đây bất cứ khi nào bạn muốn!"}};
   }

   public static String[] getTextOut() {
      return new String[]{"Bạn có thể ra khỏi nơi này bằng cách đi đến nơi mũi tên chỉ"};
   }

   public static String getMoney() {
      return MapScr.isNewVersion ? "xeng" : xu;
   }

   public static String getMoneyH() {
      return MapScr.isNewVersion ? "xèng" : xu;
   }
}
